---
- include: setup-regular-user.yml

- include: setup-ansible-user.yml

# This includes a dist-upgrade  
- include: packages.yml

# time setting
- include: system.yml

# authentication
- include: authentication.yml

- include: security.yml
