--- # Install all the standard packages:
# apt, pip, and other package managers included.

- name: packages - apt update && apt dist-upgrade *MAY TAKE A LONG TIME*
  apt:
    update_cache: yes
    upgrade: dist

# keep alphabetically ordered
- name: packages - install our standard additions to the base install
  apt:
    state: latest
    pkg:
      - curl
      - dnsutils
      - jq
      - nmap
      - python3-pip
      - ranger
      - rsyslog-gnutls
      - tcpdump
      - tmux
      - ufw
      - vim

# apt - cleanup
- name: packages - apt-get autoremove
  apt:
    autoremove: yes

# pip - install pip3 packages
- name: packages - install our additional pip packages
  pip:
    state: latest
    executable: pip3
    name:
      - pip # self upgrade pip first
      - glances
      - bottle
