---
# Sudo Group Setup
- name: Make sure we have a 'sudo' group
  group:
    name: sudo
    state: present
 
- name: Allow created user to have passwordless sudo
  lineinfile:
    path: /etc/sudoers
    state: present
    line: "{{ ansible_username }} ALL=(ALL) NOPASSWD: ALL"
 
# User + Key Setup
- name: Create a new regular user with sudo privileges
  user:
    name: "{{ ansible_username }}"
    password: "{{ ansible_password }}"
    state: present
    groups: sudo
    append: true
    create_home: true
    shell: /bin/bash
 
- name: Set authorized key for remote user
  authorized_key:
    user: "{{ ansible_username }}"
    state: present
    key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
